//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.27 at 06:54:50 PM GMT+05:00 
//


package kz.tamur.fc.iiscon.universalservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Данные о нотарильном заверении документа
 * 
 * <p>Java class for CertifiedInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertifiedInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="notary" type="{http://schemas.letograf.kz/iiscon/bus/v1}Notary"/>
 *         &lt;element name="operator" type="{http://schemas.letograf.kz/iiscon/bus/v1}Employee"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertifiedInfo", propOrder = {
    "notary",
    "operator"
})
public class CertifiedInfo {

    protected Notary notary;
    protected Employee operator;

    /**
     * Gets the value of the notary property.
     * 
     * @return
     *     possible object is
     *     {@link Notary }
     *     
     */
    public Notary getNotary() {
        return notary;
    }

    /**
     * Sets the value of the notary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notary }
     *     
     */
    public void setNotary(Notary value) {
        this.notary = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link Employee }
     *     
     */
    public Employee getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Employee }
     *     
     */
    public void setOperator(Employee value) {
        this.operator = value;
    }

}
