//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.27 at 06:54:50 PM GMT+05:00 
//


package kz.tamur.fc.iiscon.universalservice;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CopyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CopyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ORIGINAL"/>
 *     &lt;enumeration value="COPY"/>
 *     &lt;enumeration value="NOTARIZED_COPY"/>
 *     &lt;enumeration value="ELECTRONIC"/>
 *     &lt;enumeration value="WAIT_ELECTRONIC"/>
 *     &lt;enumeration value="DUBLICATE"/>
 *     &lt;enumeration value="ARCHIVE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CopyType")
@XmlEnum
public enum CopyType {


    /**
     * Оригинал
     * 
     */
    ORIGINAL,

    /**
     * Копия
     * 
     */
    COPY,

    /**
     * Нотариально заверенная копия
     * 
     */
    NOTARIZED_COPY,

    /**
     * Электронный документ
     * 
     */
    ELECTRONIC,

    /**
     * Ожидается получение документа от ГО. Используется при асинхронном взаимодействии.
     * 
     */
    WAIT_ELECTRONIC,

    /**
     * Дубликат
     * 
     */
    DUBLICATE,

    /**
     * Архивный документ (справка)
     * 
     */
    ARCHIVE;

    public String value() {
        return name();
    }

    public static CopyType fromValue(String v) {
        return valueOf(v);
    }

}
