//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.27 at 06:54:50 PM GMT+05:00 
//


package kz.tamur.fc.iiscon.universalservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Справочник видов услуг
 * 
 * <p>Java class for DicServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DicServiceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.letograf.kz/iiscon/bus/v1}DicAbstract">
 *       &lt;sequence>
 *         &lt;element name="servCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serviceWeight" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="isPaid" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ministryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DicServiceType", propOrder = {
    "servCategory",
    "serviceWeight",
    "isPaid",
    "ministryCode"
})
public class DicServiceType
    extends DicAbstract
{

    @XmlElement(required = true)
    protected String servCategory;
    @XmlSchemaType(name = "unsignedShort")
    protected int serviceWeight;
    protected boolean isPaid;
    protected String ministryCode;

    /**
     * Gets the value of the servCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServCategory() {
        return servCategory;
    }

    /**
     * Sets the value of the servCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServCategory(String value) {
        this.servCategory = value;
    }

    /**
     * Gets the value of the serviceWeight property.
     * 
     */
    public int getServiceWeight() {
        return serviceWeight;
    }

    /**
     * Sets the value of the serviceWeight property.
     * 
     */
    public void setServiceWeight(int value) {
        this.serviceWeight = value;
    }

    /**
     * Gets the value of the isPaid property.
     * 
     */
    public boolean isIsPaid() {
        return isPaid;
    }

    /**
     * Sets the value of the isPaid property.
     * 
     */
    public void setIsPaid(boolean value) {
        this.isPaid = value;
    }

    /**
     * Gets the value of the ministryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinistryCode() {
        return ministryCode;
    }

    /**
     * Sets the value of the ministryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinistryCode(String value) {
        this.ministryCode = value;
    }

}
