//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.27 at 06:54:50 PM GMT+05:00 
//


package kz.tamur.fc.iiscon.universalservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Ответ ШЭП
 * 
 * <p>Java class for QueryEGovGateResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryEGovGateResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="errorMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="responseBody" type="{http://schemas.letograf.kz/iiscon/bus/v1}Any" minOccurs="0"/>
 *         &lt;element name="responseDocuments" type="{http://schemas.letograf.kz/iiscon/bus/v1}Documents" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryEGovGateResponse", propOrder = {
    "requestId",
    "errorMessage",
    "responseBody",
    "responseDocuments"
})
public class QueryEGovGateResponse {

    @XmlElement(required = true)
    protected String requestId;
    protected String errorMessage;
    protected Any responseBody;
    protected Documents responseDocuments;

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the errorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Sets the value of the errorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMessage(String value) {
        this.errorMessage = value;
    }

    /**
     * Gets the value of the responseBody property.
     * 
     * @return
     *     possible object is
     *     {@link Any }
     *     
     */
    public Any getResponseBody() {
        return responseBody;
    }

    /**
     * Sets the value of the responseBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link Any }
     *     
     */
    public void setResponseBody(Any value) {
        this.responseBody = value;
    }

    /**
     * Gets the value of the responseDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link Documents }
     *     
     */
    public Documents getResponseDocuments() {
        return responseDocuments;
    }

    /**
     * Sets the value of the responseDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Documents }
     *     
     */
    public void setResponseDocuments(Documents value) {
        this.responseDocuments = value;
    }

}
