//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.27 at 06:54:50 PM GMT+05:00 
//


package kz.tamur.fc.iiscon.universalservice;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for refuseReasonType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="refuseReasonType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="INCORRECT_DATA"/>
 *     &lt;enumeration value="INCORRECT_DOCUMENTS"/>
 *     &lt;enumeration value="MVD_FAILED_THEORY"/>
 *     &lt;enumeration value="MVD_FAILED_PRACTICE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "refuseReasonType")
@XmlEnum
public enum RefuseReasonType {


    /**
     * Переданы некорректные данные
     * 
     */
    INCORRECT_DATA,

    /**
     * Переданы некорректные документы
     * 
     */
    INCORRECT_DOCUMENTS,

    /**
     * Не сдан экзамен ПДД
     * 
     */
    MVD_FAILED_THEORY,

    /**
     * Не сдан экзамен по вождению
     * 
     */
    MVD_FAILED_PRACTICE;

    public String value() {
        return name();
    }

    public static RefuseReasonType fromValue(String v) {
        return valueOf(v);
    }

}
