//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.18 at 09:26:53 AM ALMT 
//


package kz.tamur.fc.insurance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Тип данных, обозначающий информацию о запросе
 * 
 * <p>Java class for RequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdSubService" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="checkFlRequest" type="{http://insurance.fc.tamur.kz}checkFlRequestType" minOccurs="0"/>
 *         &lt;element name="createRecordRequest" type="{http://insurance.fc.tamur.kz}createRecordRequestType" minOccurs="0"/>
 *         &lt;element name="statusRequest" type="{http://insurance.fc.tamur.kz}getStatusRequestType" minOccurs="0"/>
 *         &lt;element name="closeRecordRequest" type="{http://insurance.fc.tamur.kz}closeRecordRequestType" minOccurs="0"/>
 *         &lt;element name="filePropertyRequest" type="{http://insurance.fc.tamur.kz}filePropertyRequestType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestType", propOrder = {
    "idSubService",
    "checkFlRequest",
    "createRecordRequest",
    "statusRequest",
    "closeRecordRequest",
    "filePropertyRequest"
})
public class RequestType {

    @XmlElement(name = "IdSubService", required = true)
    protected String idSubService;
    protected CheckFlRequestType checkFlRequest;
    protected CreateRecordRequestType createRecordRequest;
    protected GetStatusRequestType statusRequest;
    protected CloseRecordRequestType closeRecordRequest;
    protected FilePropertyRequestType filePropertyRequest;

    /**
     * Gets the value of the idSubService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSubService() {
        return idSubService;
    }

    /**
     * Sets the value of the idSubService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdSubService(String value) {
        this.idSubService = value;
    }

    /**
     * Gets the value of the checkFlRequest property.
     * 
     * @return
     *     possible object is
     *     {@link CheckFlRequestType }
     *     
     */
    public CheckFlRequestType getCheckFlRequest() {
        return checkFlRequest;
    }

    /**
     * Sets the value of the checkFlRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckFlRequestType }
     *     
     */
    public void setCheckFlRequest(CheckFlRequestType value) {
        this.checkFlRequest = value;
    }

    /**
     * Gets the value of the createRecordRequest property.
     * 
     * @return
     *     possible object is
     *     {@link CreateRecordRequestType }
     *     
     */
    public CreateRecordRequestType getCreateRecordRequest() {
        return createRecordRequest;
    }

    /**
     * Sets the value of the createRecordRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateRecordRequestType }
     *     
     */
    public void setCreateRecordRequest(CreateRecordRequestType value) {
        this.createRecordRequest = value;
    }

    /**
     * Gets the value of the statusRequest property.
     * 
     * @return
     *     possible object is
     *     {@link GetStatusRequestType }
     *     
     */
    public GetStatusRequestType getStatusRequest() {
        return statusRequest;
    }

    /**
     * Sets the value of the statusRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetStatusRequestType }
     *     
     */
    public void setStatusRequest(GetStatusRequestType value) {
        this.statusRequest = value;
    }

    /**
     * Gets the value of the closeRecordRequest property.
     * 
     * @return
     *     possible object is
     *     {@link CloseRecordRequestType }
     *     
     */
    public CloseRecordRequestType getCloseRecordRequest() {
        return closeRecordRequest;
    }

    /**
     * Sets the value of the closeRecordRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CloseRecordRequestType }
     *     
     */
    public void setCloseRecordRequest(CloseRecordRequestType value) {
        this.closeRecordRequest = value;
    }

    /**
     * Gets the value of the filePropertyRequest property.
     * 
     * @return
     *     possible object is
     *     {@link FilePropertyRequestType }
     *     
     */
    public FilePropertyRequestType getFilePropertyRequest() {
        return filePropertyRequest;
    }

    /**
     * Sets the value of the filePropertyRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilePropertyRequestType }
     *     
     */
    public void setFilePropertyRequest(FilePropertyRequestType value) {
        this.filePropertyRequest = value;
    }

}
