//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.23 at 04:01:18 PM ALMT 
//


package kz.tamur.fc.el.licensesearch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TaxpayerLicense complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxpayerLicense">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LicenseSeries" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LicenseNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GlobalUniqueNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ActivityType" type="{http://integration.elicense.kz/CustomServices/Egov/EgovLicenseSearchService}DictionaryRecord" minOccurs="0"/>
 *         &lt;element name="Licensiar" type="{http://integration.elicense.kz/CustomServices/Egov/EgovLicenseSearchService}DictionaryRecord" minOccurs="0"/>
 *         &lt;element name="DateIssue" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ValidityStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ValidityEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="LicActivityType" type="{http://integration.elicense.kz/CustomServices/Egov/EgovLicenseSearchService}LicenseActivityType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxpayerLicense", propOrder = {
    "licenseSeries",
    "licenseNumber",
    "globalUniqueNumber",
    "activityType",
    "licensiar",
    "dateIssue",
    "validityStartDate",
    "validityEndDate",
    "licActivityType"
})
public class TaxpayerLicense {

    @XmlElement(name = "LicenseSeries")
    protected String licenseSeries;
    @XmlElement(name = "LicenseNumber")
    protected String licenseNumber;
    @XmlElement(name = "GlobalUniqueNumber")
    protected String globalUniqueNumber;
    @XmlElement(name = "ActivityType")
    protected DictionaryRecord activityType;
    @XmlElement(name = "Licensiar")
    protected DictionaryRecord licensiar;
    @XmlElement(name = "DateIssue", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateIssue;
    @XmlElement(name = "ValidityStartDate", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validityStartDate;
    @XmlElement(name = "ValidityEndDate", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validityEndDate;
    @XmlElement(name = "LicActivityType", required = true)
    protected LicenseActivityType licActivityType;

    /**
     * Gets the value of the licenseSeries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseSeries() {
        return licenseSeries;
    }

    /**
     * Sets the value of the licenseSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseSeries(String value) {
        this.licenseSeries = value;
    }

    /**
     * Gets the value of the licenseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseNumber() {
        return licenseNumber;
    }

    /**
     * Sets the value of the licenseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseNumber(String value) {
        this.licenseNumber = value;
    }

    /**
     * Gets the value of the globalUniqueNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalUniqueNumber() {
        return globalUniqueNumber;
    }

    /**
     * Sets the value of the globalUniqueNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalUniqueNumber(String value) {
        this.globalUniqueNumber = value;
    }

    /**
     * Gets the value of the activityType property.
     * 
     * @return
     *     possible object is
     *     {@link DictionaryRecord }
     *     
     */
    public DictionaryRecord getActivityType() {
        return activityType;
    }

    /**
     * Sets the value of the activityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictionaryRecord }
     *     
     */
    public void setActivityType(DictionaryRecord value) {
        this.activityType = value;
    }

    /**
     * Gets the value of the licensiar property.
     * 
     * @return
     *     possible object is
     *     {@link DictionaryRecord }
     *     
     */
    public DictionaryRecord getLicensiar() {
        return licensiar;
    }

    /**
     * Sets the value of the licensiar property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictionaryRecord }
     *     
     */
    public void setLicensiar(DictionaryRecord value) {
        this.licensiar = value;
    }

    /**
     * Gets the value of the dateIssue property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateIssue() {
        return dateIssue;
    }

    /**
     * Sets the value of the dateIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateIssue(XMLGregorianCalendar value) {
        this.dateIssue = value;
    }

    /**
     * Gets the value of the validityStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidityStartDate() {
        return validityStartDate;
    }

    /**
     * Sets the value of the validityStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidityStartDate(XMLGregorianCalendar value) {
        this.validityStartDate = value;
    }

    /**
     * Gets the value of the validityEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidityEndDate() {
        return validityEndDate;
    }

    /**
     * Sets the value of the validityEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidityEndDate(XMLGregorianCalendar value) {
        this.validityEndDate = value;
    }

    /**
     * Gets the value of the licActivityType property.
     * 
     * @return
     *     possible object is
     *     {@link LicenseActivityType }
     *     
     */
    public LicenseActivityType getLicActivityType() {
        return licActivityType;
    }

    /**
     * Sets the value of the licActivityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicenseActivityType }
     *     
     */
    public void setLicActivityType(LicenseActivityType value) {
        this.licActivityType = value;
    }

}
