package com.cifs.or2.kernel;


/**
* com/cifs/or2/kernel/BlobValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/com/cifs/or2/idl/kernel.idl
* 27 Август 2009 г. 4:40:10 GMT
*/

public final class BlobValue implements java.io.Serializable
{
  public long objectId = (long)0;
  public long attrId = (long)0;
  public byte value[] = null;
  public long langId = (long)0;

  public BlobValue ()
  {
  } // ctor

  public BlobValue (long _objectId, long _attrId, byte[] _value, long _langId)
  {
    objectId = _objectId;
    attrId = _attrId;
    value = _value;
    langId = _langId;
  } // ctor

} // class BlobValue
