//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.23 at 09:44:27 AM ALMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://service.2fa-chain.kz/ns/kdp")
package kz.tamur.fc.kdp.service.request;
