//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.05 at 05:24:35 PM GMT+05:00 
//


package kz.tamur.fc.keleshek;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Передача данных для создания депозита
 * 
 * <p>Java class for DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="person" type="{http://keleshek.fc.tamur.kz}PersonType" form="qualified"/>
 *         &lt;element name="deposit" type="{http://keleshek.fc.tamur.kz}RecordType" form="qualified"/>
 *         &lt;element name="docums" type="{http://keleshek.fc.tamur.kz}DictionaryType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="isOrphan" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isLargeFamily" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IINTutor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IINSecondTutor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataType", propOrder = {
    "person",
    "deposit",
    "docums",
    "isOrphan",
    "isLargeFamily",
    "iinTutor",
    "iinSecondTutor"
})
public class DataType {

    @XmlElement(required = true)
    protected PersonType person;
    @XmlElement(required = true)
    protected RecordType deposit;
    protected List<DictionaryType> docums;
    protected Boolean isOrphan;
    protected Boolean isLargeFamily;
    @XmlElement(name = "IINTutor")
    protected String iinTutor;
    @XmlElement(name = "IINSecondTutor")
    protected String iinSecondTutor;

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link PersonType }
     *     
     */
    public PersonType getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonType }
     *     
     */
    public void setPerson(PersonType value) {
        this.person = value;
    }

    /**
     * Gets the value of the deposit property.
     * 
     * @return
     *     possible object is
     *     {@link RecordType }
     *     
     */
    public RecordType getDeposit() {
        return deposit;
    }

    /**
     * Sets the value of the deposit property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordType }
     *     
     */
    public void setDeposit(RecordType value) {
        this.deposit = value;
    }

    /**
     * Gets the value of the docums property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the docums property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocums().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DictionaryType }
     * 
     * 
     */
    public List<DictionaryType> getDocums() {
        if (docums == null) {
            docums = new ArrayList<DictionaryType>();
        }
        return this.docums;
    }

    /**
     * Gets the value of the isOrphan property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsOrphan() {
        return isOrphan;
    }

    /**
     * Sets the value of the isOrphan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsOrphan(Boolean value) {
        this.isOrphan = value;
    }

    /**
     * Gets the value of the isLargeFamily property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsLargeFamily() {
        return isLargeFamily;
    }

    /**
     * Sets the value of the isLargeFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsLargeFamily(Boolean value) {
        this.isLargeFamily = value;
    }

    /**
     * Gets the value of the iinTutor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIINTutor() {
        return iinTutor;
    }

    /**
     * Sets the value of the iinTutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIINTutor(String value) {
        this.iinTutor = value;
    }

    /**
     * Gets the value of the iinSecondTutor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIINSecondTutor() {
        return iinSecondTutor;
    }

    /**
     * Sets the value of the iinSecondTutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIINSecondTutor(String value) {
        this.iinSecondTutor = value;
    }

}
