//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.05 at 05:24:35 PM GMT+05:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://keleshek.fc.tamur.kz", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kz.tamur.fc.keleshek;
