package kz.tamur.or3.mtszn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-08-05T09:51:27.176+06:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://services.sync.mtszn/", name = "SyncService")
@XmlSeeAlso({kz.tamur.or3.mtszn.epay.ObjectFactory.class, kz.tamur.or3.mtszn.mvdvuinfo.ObjectFactory.class, ObjectFactory.class, kz.tamur.or3.mtszn.systeminfo.ObjectFactory.class, kz.tamur.or3.mtszn.dict.ObjectFactory.class, kz.tamur.or3.mtszn.akimat.ObjectFactory.class, kz.tamur.or3.mtszn.doc.ObjectFactory.class, kz.tamur.or3.mtszn.bas.ObjectFactory.class, kz.tamur.or3.mtszn.nataddress.ObjectFactory.class, kz.tamur.or3.mtszn.igcvp.ObjectFactory.class, kz.tamur.or3.mtszn.birth.ObjectFactory.class, kz.tamur.or3.mtszn.natperson.ObjectFactory.class, kz.tamur.or3.mtszn.mvd.ObjectFactory.class})
public interface SyncService {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06560Request", output = "http://services.sync.mtszn/SyncService/getP06560Response")
    @RequestWrapper(localName = "getP06560", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06560")
    @WebMethod
    @ResponseWrapper(localName = "getP06560Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06560Response")
    public kz.tamur.or3.mtszn.P06560Response getP06560(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06560Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06556Request", output = "http://services.sync.mtszn/SyncService/getP06556Response")
    @RequestWrapper(localName = "getP06556", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06556")
    @WebMethod
    @ResponseWrapper(localName = "getP06556Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06556Response")
    public kz.tamur.or3.mtszn.P06556Response getP06556(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06556Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06554Request", output = "http://services.sync.mtszn/SyncService/getP06554Response")
    @RequestWrapper(localName = "getP06554", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06554")
    @WebMethod
    @ResponseWrapper(localName = "getP06554Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06554Response")
    public kz.tamur.or3.mtszn.P06554Response getP06554(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06554Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06557Request", output = "http://services.sync.mtszn/SyncService/getP06557Response")
    @RequestWrapper(localName = "getP06557", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06557")
    @WebMethod
    @ResponseWrapper(localName = "getP06557Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06557Response")
    public kz.tamur.or3.mtszn.P06557Response getP06557(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06557Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06563Request", output = "http://services.sync.mtszn/SyncService/getP06563Response")
    @RequestWrapper(localName = "getP06563", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06563")
    @WebMethod
    @ResponseWrapper(localName = "getP06563Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06563Response")
    public kz.tamur.or3.mtszn.bas.P06563Response getP06563(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.bas.P06563Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06590Request", output = "http://services.sync.mtszn/SyncService/getP06590Response")
    @RequestWrapper(localName = "getP06590", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06590")
    @WebMethod
    @ResponseWrapper(localName = "getP06590Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06590Response")
    public kz.tamur.or3.mtszn.P06590Response getP06590(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06590Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06555Request", output = "http://services.sync.mtszn/SyncService/getP06555Response")
    @RequestWrapper(localName = "getP06555", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06555")
    @WebMethod
    @ResponseWrapper(localName = "getP06555Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06555Response")
    public kz.tamur.or3.mtszn.P06555Response getP06555(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06555Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06580Request", output = "http://services.sync.mtszn/SyncService/getP06580Response")
    @RequestWrapper(localName = "getP06580", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06580")
    @WebMethod
    @ResponseWrapper(localName = "getP06580Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06580Response")
    public kz.tamur.or3.mtszn.P06580Response getP06580(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06580Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06561Request", output = "http://services.sync.mtszn/SyncService/getP06561Response")
    @RequestWrapper(localName = "getP06561", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06561")
    @WebMethod
    @ResponseWrapper(localName = "getP06561Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06561Response")
    public kz.tamur.or3.mtszn.P06561Response getP06561(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06561Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06558Request", output = "http://services.sync.mtszn/SyncService/getP06558Response")
    @RequestWrapper(localName = "getP06558", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06558")
    @WebMethod
    @ResponseWrapper(localName = "getP06558Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06558Response")
    public kz.tamur.or3.mtszn.P06558Response getP06558(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06558Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06582Request", output = "http://services.sync.mtszn/SyncService/getP06582Response")
    @RequestWrapper(localName = "getP06582", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06582")
    @WebMethod
    @ResponseWrapper(localName = "getP06582Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06582Response")
    public kz.tamur.or3.mtszn.P06582Response getP06582(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06582Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06559Request", output = "http://services.sync.mtszn/SyncService/getP06559Response")
    @RequestWrapper(localName = "getP06559", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06559")
    @WebMethod
    @ResponseWrapper(localName = "getP06559Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06559Response")
    public kz.tamur.or3.mtszn.P06559Response getP06559(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06559Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06552Request", output = "http://services.sync.mtszn/SyncService/getP06552Response")
    @RequestWrapper(localName = "getP06552", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06552")
    @WebMethod
    @ResponseWrapper(localName = "getP06552Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06552Response")
    public kz.tamur.or3.mtszn.P06552Response getP06552(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06552Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06581Request", output = "http://services.sync.mtszn/SyncService/getP06581Response")
    @RequestWrapper(localName = "getP06581", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06581")
    @WebMethod
    @ResponseWrapper(localName = "getP06581Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06581Response")
    public kz.tamur.or3.mtszn.P06581Response getP06581(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06581Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06562Request", output = "http://services.sync.mtszn/SyncService/getP06562Response")
    @RequestWrapper(localName = "getP06562", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06562")
    @WebMethod
    @ResponseWrapper(localName = "getP06562Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06562Response")
    public kz.tamur.or3.mtszn.P06562Response getP06562(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06562Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06553Request", output = "http://services.sync.mtszn/SyncService/getP06553Response")
    @RequestWrapper(localName = "getP06553", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06553")
    @WebMethod
    @ResponseWrapper(localName = "getP06553Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06553Response")
    public kz.tamur.or3.mtszn.P06553Response getP06553(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06553Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06551Request", output = "http://services.sync.mtszn/SyncService/getP06551Response")
    @RequestWrapper(localName = "getP06551", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06551")
    @WebMethod
    @ResponseWrapper(localName = "getP06551Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06551Response")
    public kz.tamur.or3.mtszn.P06551Response getP06551(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06551Request request
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://services.sync.mtszn/SyncService/getP06591Request", output = "http://services.sync.mtszn/SyncService/getP06591Response")
    @RequestWrapper(localName = "getP06591", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06591")
    @WebMethod
    @ResponseWrapper(localName = "getP06591Response", targetNamespace = "http://services.sync.mtszn/", className = "kz.tamur.or3.mtszn.GetP06591Response")
    public kz.tamur.or3.mtszn.P06591Response getP06591(
        @WebParam(name = "request", targetNamespace = "")
        kz.tamur.or3.mtszn.P06591Request request
    );
}
