package kz.tamur.or3.mtszn;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-08-05T09:51:27.212+06:00
 * Generated source version: 3.0.0
 * 
 */
@WebServiceClient(name = "SyncServiceService", 
                  wsdlLocation = "SyncServicePort.wsdl",
                  targetNamespace = "http://services.sync.mtszn/") 
public class SyncServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.sync.mtszn/", "SyncServiceService");
    public final static QName SyncServicePort = new QName("http://services.sync.mtszn/", "SyncServicePort");
    static {
        URL url = SyncServiceService.class.getResource("SyncServicePort.wsdl");
        if (url == null) {
            url = SyncServiceService.class.getClassLoader().getResource("SyncServicePort.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(SyncServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "SyncServicePort.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SyncServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SyncServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SyncServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return
     *     returns SyncService
     */
    @WebEndpoint(name = "SyncServicePort")
    public SyncService getSyncServicePort() {
        return super.getPort(SyncServicePort, SyncService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SyncService
     */
    @WebEndpoint(name = "SyncServicePort")
    public SyncService getSyncServicePort(WebServiceFeature... features) {
        return super.getPort(SyncServicePort, SyncService.class, features);
    }

}
