//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.08 at 04:15:17 PM ALMT 
//


package kz.tamur.fc.gbdul.infobybin.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Основной тип, описывающий сведения об ИПс Нерезидентов
 * 
 * <p>Java class for IpsNerezType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IpsNerezType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RegDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="LiquidationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="FullNameRu" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrgForm" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}DirectoryType"/>
 *         &lt;element name="CountryFac" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CountryNerezident" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}DirectoryType" minOccurs="0"/>
 *         &lt;element name="RegStatus" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}DirectoryType"/>
 *         &lt;element name="Leader" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}LeaderIpsNerezType" minOccurs="0"/>
 *         &lt;element name="Address" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}AddressIpsNerezType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IpsNerezType", propOrder = {
    "bin",
    "regDate",
    "liquidationDate",
    "fullNameRu",
    "orgForm",
    "countryFac",
    "countryNerezident",
    "regStatus",
    "leader",
    "address"
})
public class IpsNerezType {

    @XmlElement(name = "BIN", required = true)
    protected String bin;
    @XmlElement(name = "RegDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar regDate;
    @XmlElement(name = "LiquidationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar liquidationDate;
    @XmlElement(name = "FullNameRu", required = true)
    protected String fullNameRu;
    @XmlElement(name = "OrgForm", required = true)
    protected DirectoryType orgForm;
    @XmlElement(name = "CountryFac")
    protected Boolean countryFac;
    @XmlElement(name = "CountryNerezident")
    protected DirectoryType countryNerezident;
    @XmlElement(name = "RegStatus", required = true)
    protected DirectoryType regStatus;
    @XmlElement(name = "Leader")
    protected LeaderIpsNerezType leader;
    @XmlElement(name = "Address")
    protected AddressIpsNerezType address;

    /**
     * Gets the value of the bin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIN() {
        return bin;
    }

    /**
     * Sets the value of the bin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIN(String value) {
        this.bin = value;
    }

    /**
     * Gets the value of the regDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRegDate() {
        return regDate;
    }

    /**
     * Sets the value of the regDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRegDate(XMLGregorianCalendar value) {
        this.regDate = value;
    }

    /**
     * Gets the value of the liquidationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLiquidationDate() {
        return liquidationDate;
    }

    /**
     * Sets the value of the liquidationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLiquidationDate(XMLGregorianCalendar value) {
        this.liquidationDate = value;
    }

    /**
     * Gets the value of the fullNameRu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullNameRu() {
        return fullNameRu;
    }

    /**
     * Sets the value of the fullNameRu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullNameRu(String value) {
        this.fullNameRu = value;
    }

    /**
     * Gets the value of the orgForm property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryType }
     *     
     */
    public DirectoryType getOrgForm() {
        return orgForm;
    }

    /**
     * Sets the value of the orgForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryType }
     *     
     */
    public void setOrgForm(DirectoryType value) {
        this.orgForm = value;
    }

    /**
     * Gets the value of the countryFac property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCountryFac() {
        return countryFac;
    }

    /**
     * Sets the value of the countryFac property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCountryFac(Boolean value) {
        this.countryFac = value;
    }

    /**
     * Gets the value of the countryNerezident property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryType }
     *     
     */
    public DirectoryType getCountryNerezident() {
        return countryNerezident;
    }

    /**
     * Sets the value of the countryNerezident property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryType }
     *     
     */
    public void setCountryNerezident(DirectoryType value) {
        this.countryNerezident = value;
    }

    /**
     * Gets the value of the regStatus property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryType }
     *     
     */
    public DirectoryType getRegStatus() {
        return regStatus;
    }

    /**
     * Sets the value of the regStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryType }
     *     
     */
    public void setRegStatus(DirectoryType value) {
        this.regStatus = value;
    }

    /**
     * Gets the value of the leader property.
     * 
     * @return
     *     possible object is
     *     {@link LeaderIpsNerezType }
     *     
     */
    public LeaderIpsNerezType getLeader() {
        return leader;
    }

    /**
     * Sets the value of the leader property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeaderIpsNerezType }
     *     
     */
    public void setLeader(LeaderIpsNerezType value) {
        this.leader = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressIpsNerezType }
     *     
     */
    public AddressIpsNerezType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressIpsNerezType }
     *     
     */
    public void setAddress(AddressIpsNerezType value) {
        this.address = value;
    }

}
