//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.08 at 04:20:52 PM ALMT 
//


package kz.tamur.fc.gbdul.signup.actualdata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Тип, описывающий сведения о прекращении деятельности
 * 
 * <p>Java class for LiquidationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LiquidationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LiquidationType" type="{http://newshep.gbdulsignupactualdata.gbdul.tamur.kz}DictionaryType"/>
 *         &lt;element name="LiquidationBase" type="{http://newshep.gbdulsignupactualdata.gbdul.tamur.kz}DictionaryType"/>
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="AssigneeBIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LiquidationInfoType", propOrder = {
    "liquidationType",
    "liquidationBase",
    "date",
    "assigneeBIN"
})
public class LiquidationInfoType {

    @XmlElement(name = "LiquidationType", required = true)
    protected DictionaryType liquidationType;
    @XmlElement(name = "LiquidationBase", required = true)
    protected DictionaryType liquidationBase;
    @XmlElement(name = "Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "AssigneeBIN")
    protected String assigneeBIN;

    /**
     * Gets the value of the liquidationType property.
     * 
     * @return
     *     possible object is
     *     {@link DictionaryType }
     *     
     */
    public DictionaryType getLiquidationType() {
        return liquidationType;
    }

    /**
     * Sets the value of the liquidationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictionaryType }
     *     
     */
    public void setLiquidationType(DictionaryType value) {
        this.liquidationType = value;
    }

    /**
     * Gets the value of the liquidationBase property.
     * 
     * @return
     *     possible object is
     *     {@link DictionaryType }
     *     
     */
    public DictionaryType getLiquidationBase() {
        return liquidationBase;
    }

    /**
     * Sets the value of the liquidationBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictionaryType }
     *     
     */
    public void setLiquidationBase(DictionaryType value) {
        this.liquidationBase = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the assigneeBIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssigneeBIN() {
        return assigneeBIN;
    }

    /**
     * Sets the value of the assigneeBIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssigneeBIN(String value) {
        this.assigneeBIN = value;
    }

}
