//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.08 at 04:23:59 PM ALMT 
//


package kz.tamur.fc.gbdul.signup.spisokbin;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kz.tamur.fc.gbdul.signup.spisokbin package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Request_QNAME = new QName("http://newshep.gbdulsignupspisokbin.gbdul.tamur.kz", "Request");
    private final static QName _Response_QNAME = new QName("http://newshep.gbdulsignupspisokbin.gbdul.tamur.kz", "Response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kz.tamur.fc.gbdul.signup.spisokbin
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResponseMessage }
     * 
     */
    public ResponseMessage createResponseMessage() {
        return new ResponseMessage();
    }

    /**
     * Create an instance of {@link RequestMessage }
     * 
     */
    public RequestMessage createRequestMessage() {
        return new RequestMessage();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link DirectoryType }
     * 
     */
    public DirectoryType createDirectoryType() {
        return new DirectoryType();
    }

    /**
     * Create an instance of {@link BINListType }
     * 
     */
    public BINListType createBINListType() {
        return new BINListType();
    }

    /**
     * Create an instance of {@link ErrorListType }
     * 
     */
    public ErrorListType createErrorListType() {
        return new ErrorListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://newshep.gbdulsignupspisokbin.gbdul.tamur.kz", name = "Request")
    public JAXBElement<RequestMessage> createRequest(RequestMessage value) {
        return new JAXBElement<RequestMessage>(_Request_QNAME, RequestMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://newshep.gbdulsignupspisokbin.gbdul.tamur.kz", name = "Response")
    public JAXBElement<ResponseMessage> createResponse(ResponseMessage value) {
        return new JAXBElement<ResponseMessage>(_Response_QNAME, ResponseMessage.class, null, value);
    }

}
