
package kz.tamur.gbdul.egp.dir;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "DirectoryServiceService", targetNamespace = "http://impl.egp.gbdul.tamur.kz/", wsdlLocation = "./directory.wsdl")
public class DirectoryServiceService
    extends Service
{
    public DirectoryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DirectoryServiceService() {
        super(kz.tamur.gbdul.egp.dir.DirectoryServiceService.class.getResource("directory.wsdl"), new QName("http://impl.egp.gbdul.tamur.kz/", "DirectoryServiceService"));
    }

    /**
     * 
     * @return
     *     returns DirectoryService
     */
    @WebEndpoint(name = "DirectoryServicePort")
    public DirectoryService getDirectoryServicePort() {
        return super.getPort(new QName("http://impl.egp.gbdul.tamur.kz/", "DirectoryServicePort"), DirectoryService.class);
    }

}
