//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.29 at 05:55:27 PM ALMT 
//


package kz.tamur.fc.nobd.actualization.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Response complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Response">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dataObject">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dataObject" type="{}DataObject" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="schoolObject">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="schoolObject" type="{}SchoolObject" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Response", propOrder = {
    "dataObject",
    "schoolObject"
})
public class Response {

    @XmlElement(required = true)
    protected Response.DataObject dataObject;
    @XmlElement(required = true)
    protected Response.SchoolObject schoolObject;

    /**
     * Gets the value of the dataObject property.
     * 
     * @return
     *     possible object is
     *     {@link Response.DataObject }
     *     
     */
    public Response.DataObject getDataObject() {
        return dataObject;
    }

    /**
     * Sets the value of the dataObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response.DataObject }
     *     
     */
    public void setDataObject(Response.DataObject value) {
        this.dataObject = value;
    }

    /**
     * Gets the value of the schoolObject property.
     * 
     * @return
     *     possible object is
     *     {@link Response.SchoolObject }
     *     
     */
    public Response.SchoolObject getSchoolObject() {
        return schoolObject;
    }

    /**
     * Sets the value of the schoolObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response.SchoolObject }
     *     
     */
    public void setSchoolObject(Response.SchoolObject value) {
        this.schoolObject = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dataObject" type="{}DataObject" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataObject"
    })
    public static class DataObject {

        @XmlElement(required = true)
        protected List<kz.tamur.fc.nobd.actualization.response.DataObject> dataObject;

        /**
         * Gets the value of the dataObject property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dataObject property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDataObject().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link kz.tamur.fc.nobd.actualization.response.DataObject }
         * 
         * 
         */
        public List<kz.tamur.fc.nobd.actualization.response.DataObject> getDataObject() {
            if (dataObject == null) {
                dataObject = new ArrayList<kz.tamur.fc.nobd.actualization.response.DataObject>();
            }
            return this.dataObject;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="schoolObject" type="{}SchoolObject" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "schoolObject"
    })
    public static class SchoolObject {

        @XmlElement(required = true)
        protected List<kz.tamur.fc.nobd.actualization.response.SchoolObject> schoolObject;

        /**
         * Gets the value of the schoolObject property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the schoolObject property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSchoolObject().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link kz.tamur.fc.nobd.actualization.response.SchoolObject }
         * 
         * 
         */
        public List<kz.tamur.fc.nobd.actualization.response.SchoolObject> getSchoolObject() {
            if (schoolObject == null) {
                schoolObject = new ArrayList<kz.tamur.fc.nobd.actualization.response.SchoolObject>();
            }
            return this.schoolObject;
        }

    }

}
