//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.24 at 03:16:44 PM ALMT 
//


package kz.tamur.fc.gbdrn.report303;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Сведения о правах на недвижимость
 * 
 * <p>Java class for ArrayOfGbdrnImmovablesRightType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfGbdrnImmovablesRightType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ImmovablesRight" type="{http://types.303.reports.egov.rn3.tamur.kz}GbdrnImmovablesRightType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfGbdrnImmovablesRightType", propOrder = {
    "immovablesRight"
})
public class ArrayOfGbdrnImmovablesRightType {

    @XmlElement(name = "ImmovablesRight")
    protected List<GbdrnImmovablesRightType> immovablesRight;

    /**
     * Gets the value of the immovablesRight property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the immovablesRight property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImmovablesRight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GbdrnImmovablesRightType }
     * 
     * 
     */
    public List<GbdrnImmovablesRightType> getImmovablesRight() {
        if (immovablesRight == null) {
            immovablesRight = new ArrayList<GbdrnImmovablesRightType>();
        }
        return this.immovablesRight;
    }

}
