//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.08 at 02:49:42 PM ALMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservices.actualization.kz/EducationDataActualizationService/schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kz.tamur.fc.nobd.actualization;
