//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.08 at 04:35:41 PM ALMT 
//


package kz.tamur.fc.mon.nedb.universal.request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kz.tamur.fc.mon.nedb.universal.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataRequestWrapper_QNAME = new QName("", "dataRequestWrapper");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kz.tamur.fc.mon.nedb.universal.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataRequestWrapper }
     * 
     */
    public DataRequestWrapper createDataRequestWrapper() {
        return new DataRequestWrapper();
    }

    /**
     * Create an instance of {@link DataRequestWrapper.Params }
     * 
     */
    public DataRequestWrapper.Params createDataRequestWrapperParams() {
        return new DataRequestWrapper.Params();
    }

    /**
     * Create an instance of {@link DataRequestWrapper.Params.Entry }
     * 
     */
    public DataRequestWrapper.Params.Entry createDataRequestWrapperParamsEntry() {
        return new DataRequestWrapper.Params.Entry();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataRequestWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataRequestWrapper")
    public JAXBElement<DataRequestWrapper> createDataRequestWrapper(DataRequestWrapper value) {
        return new JAXBElement<DataRequestWrapper>(_DataRequestWrapper_QNAME, DataRequestWrapper.class, null, value);
    }

}
