//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.26 at 10:02:00 AM ALMT 
//


package kz.tamur.fc.egov.notification.request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kz.tamur.fc.egov.notification.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NotificationRequest_QNAME = new QName("http://notification-v2.egov.bee.kz/", "notificationRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kz.tamur.fc.egov.notification.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Notification }
     * 
     */
    public Notification createNotification() {
        return new Notification();
    }

    /**
     * Create an instance of {@link NotificationRequest }
     * 
     */
    public NotificationRequest createNotificationRequest() {
        return new NotificationRequest();
    }

    /**
     * Create an instance of {@link SenderInfo }
     * 
     */
    public SenderInfo createSenderInfo() {
        return new SenderInfo();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Resources }
     * 
     */
    public Resources createResources() {
        return new Resources();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Notification.Properties }
     * 
     */
    public Notification.Properties createNotificationProperties() {
        return new Notification.Properties();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotificationRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://notification-v2.egov.bee.kz/", name = "notificationRequest")
    public JAXBElement<NotificationRequest> createNotificationRequest(NotificationRequest value) {
        return new JAXBElement<NotificationRequest>(_NotificationRequest_QNAME, NotificationRequest.class, null, value);
    }

}
