//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.08 at 12:48:51 PM ALMT 
//


package kz.tamur.fc.kazpost.gep;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kz.tamur.fc.kazpost.gep package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SendRPORequest_QNAME = new QName("http://webservices.kazpost.kz/NewHybridMailSB/schema", "SendRPORequest");
    private final static QName _ResponseInfo_QNAME = new QName("http://webservices.kazpost.kz/NewHybridMailSB/schema", "ResponseInfo");
    private final static QName _SendRPOResponse_QNAME = new QName("http://webservices.kazpost.kz/NewHybridMailSB/schema", "SendRPOResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kz.tamur.fc.kazpost.gep
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResponseInfo }
     * 
     */
    public ResponseInfo createResponseInfo() {
        return new ResponseInfo();
    }

    /**
     * Create an instance of {@link SendRPORequest }
     * 
     */
    public SendRPORequest createSendRPORequest() {
        return new SendRPORequest();
    }

    /**
     * Create an instance of {@link SendRPOResponse }
     * 
     */
    public SendRPOResponse createSendRPOResponse() {
        return new SendRPOResponse();
    }

    /**
     * Create an instance of {@link RPOInfo }
     * 
     */
    public RPOInfo createRPOInfo() {
        return new RPOInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendRPORequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.kazpost.kz/NewHybridMailSB/schema", name = "SendRPORequest")
    public JAXBElement<SendRPORequest> createSendRPORequest(SendRPORequest value) {
        return new JAXBElement<SendRPORequest>(_SendRPORequest_QNAME, SendRPORequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.kazpost.kz/NewHybridMailSB/schema", name = "ResponseInfo")
    public JAXBElement<ResponseInfo> createResponseInfo(ResponseInfo value) {
        return new JAXBElement<ResponseInfo>(_ResponseInfo_QNAME, ResponseInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendRPOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.kazpost.kz/NewHybridMailSB/schema", name = "SendRPOResponse")
    public JAXBElement<SendRPOResponse> createSendRPOResponse(SendRPOResponse value) {
        return new JAXBElement<SendRPOResponse>(_SendRPOResponse_QNAME, SendRPOResponse.class, null, value);
    }

}
