//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.07 at 12:27:01 PM ALMT 
//


package kz.tamur.shep.sed.info;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ������ ������� ��� ��������� ������ ���������� � ����������
 * 
 * <p>Java class for GetDocumentInfosRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetDocumentInfosRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="filters" type="{http://egov.bee.kz/eds/scanneddocuments/info/v1/}DocumentFilter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sort" type="{http://egov.bee.kz/eds/scanneddocuments/info/v1/}DocumentSort" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="credentials" type="{http://egov.bee.kz/eds/common/v1/}SenderInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetDocumentInfosRequest", namespace = "http://egov.bee.kz/eds/scanneddocuments/info/v1/", propOrder = {
    "filters",
    "sort",
    "credentials"
})
@XmlRootElement
public class GetDocumentInfosRequest {

    protected List<DocumentFilter> filters;
    protected List<DocumentSort> sort;
    @XmlElement(required = true)
    protected SenderInfo credentials;

    /**
     * Gets the value of the filters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentFilter }
     * 
     * 
     */
    public List<DocumentFilter> getFilters() {
        if (filters == null) {
            filters = new ArrayList<DocumentFilter>();
        }
        return this.filters;
    }

    /**
     * Gets the value of the sort property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sort property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSort().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentSort }
     * 
     * 
     */
    public List<DocumentSort> getSort() {
        if (sort == null) {
            sort = new ArrayList<DocumentSort>();
        }
        return this.sort;
    }

    /**
     * Gets the value of the credentials property.
     * 
     * @return
     *     possible object is
     *     {@link SenderInfo }
     *     
     */
    public SenderInfo getCredentials() {
        return credentials;
    }

    /**
     * Sets the value of the credentials property.
     * 
     * @param value
     *     allowed object is
     *     {@link SenderInfo }
     *     
     */
    public void setCredentials(SenderInfo value) {
        this.credentials = value;
    }

}
