/* Generated By:JJTree: Do not edit this line. ASTConstruct.java */

package kz.tamur.lang.parser;

public class ASTConstruct extends SimpleNode {
  public ASTConstruct(int id) {
    super(id);
  }

  public ASTConstruct(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
