/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package kz.tamur.lang.parser;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTDECL = 2;
  public int JJTFUNC = 3;
  public int JJTFUNCARGS = 4;
  public int JJTSET = 5;
  public int JJTRETURN = 6;
  public int JJTBREAK = 7;
  public int JJTCONTINUE = 8;
  public int JJTIF = 9;
  public int JJTBLOCK = 10;
  public int JJTFOREACH = 11;
  public int JJTWHILE = 12;
  public int JJTVAR = 13;
  public int JJTGLOBALCALL = 14;
  public int JJTEXEC = 15;
  public int JJTMETHOD = 16;
  public int JJTTYPE = 17;
  public int JJTBINARY = 18;
  public int JJTUNARY = 19;
  public int JJTFIELD = 20;
  public int JJTACCESS = 21;
  public int JJTINDEX = 22;
  public int JJTCONSTRUCT = 23;
  public int JJTNUMBER = 24;
  public int JJTSTRING = 25;
  public int JJTBOOLEAN = 26;
  public int JJTNULL = 27;
  public int JJTTRY = 28;
  public int JJTCATCH = 29;
  public int JJTFINALLY = 30;
  public int JJTTHROW = 31;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Decl",
    "Func",
    "FuncArgs",
    "Set",
    "Return",
    "Break",
    "Continue",
    "If",
    "Block",
    "Foreach",
    "While",
    "Var",
    "GlobalCall",
    "Exec",
    "Method",
    "Type",
    "Binary",
    "Unary",
    "Field",
    "Access",
    "Index",
    "Construct",
    "Number",
    "String",
    "Boolean",
    "Null",
    "Try",
    "Catch",
    "Finally",
    "Throw",
  };
}
/* JavaCC - OriginalChecksum=504cc1865eef6d871c19658d29710285 (do not edit this line) */
