package kz.tamur.rt;

import java.util.ListResourceBundle;

/**
 * Created by IntelliJ IDEA.
 * User: Vital
 * Date: 22.04.2005
 * Time: 15:19:18
 * To change this template use File | Settings | File Templates.
 */
public class RuntimeResources_kk extends ListResourceBundle {

    public static final Object[][] contents = {
            {"applyChangesShort", "\u049aолдану"},
            {"cancelChangesShort", "Болдырмау"},
            {"backPageShort", "Алдын\u0493ы бет"},
            {"usersShort", "Пайдаланушылар"},
            {"helpShort", "Аны\u049bтама"},
            {"deleteUser", "Пайдаланушыны u04e8шіру"},
            {"signShort", "u049aол u049aою"},
 
            {"applyChanges", "\u04e8згерiстерді \u049bолдану"},
            {"cancelChanges", "\u04e8згерiстерді болдырмау"},
            {"backPage", "Алдын\u0493ы бет"},
            {"buttonRun", "Келесі \u049bадам"},
            {"nextPage", "Келесі бет"},                                   
            {"print", "Баспаға"},
            {"processMap", "Процесс схемасы"},
            {"superProcess", "Бас процесс"},
            {"subProcess", "Кіші процесс"},
            {"debugProcess", "Мін ету"},
            {"pwdChange", "\u049a\u04b1пия белгіні орнату"},
            {"exchange", "Ж\u04e9нелту/Алу"},
            {"createProcess", "Процесс \u049b\u04b1рылып жатыр!!!"},
            //Buttons description
            {"applyChangesDesc", "Енгіз\u04af интерфейстегі деректерді уа\u049bытша са\u049bтау саласына\n" +
                                 "са\u049bтайды (деректер процесс ая\u049bтал\u0493ан кезде т\u04b1ра\u049bты са\u049bтау\n" +
                                 "саласына жазылады)"},
            {"cancelChangesDesc", "Енгіз\u04af интерфейстегі деректердін м\u04d9нін ал\u0493аш\u049bы \u049bалпына келтіреді.\n" +
                                  "Ал\u0493аш\u049bы м\u04d9ні -  “\u04e8згерістерді\u049bолдану” т\u04afймешекпен са\u049bтал\u0493ан\n" +
                                  "деректердін м\u04d9ні"},
            {"backPageDesc", "Пайдаланушыны алды\u04a3\u0493ы терезеге \u049bайтып \u04d9келеді. Батырма\n" +
                             "Бас терезені\u04a3 \u04e8зінде басылмайды"},
            {"nextPageDesc", "Келесі бет"},
            {"printDesc", "Шы\u0493ыс \u049b\u04b1жаттардын т\u04e8мен т\u04afсетін басып шы\u0493ару м\u04d9зірін ашады.\n" +
                          "Егер енгізу нысанында басып шы\u0493ару м\u04afмкіндігі болмаса,\n" +
                          "батырма басылмайды"},
            {"processMapDesc", "Тапсырмалар мониторында\u0493ы б\u04e8ліп к\u04e8рсетілген жола\u0493ына\n" +
                               "процесс картасыны\u04a3 \u049bарау терезесін ашады"},
            {"superProcessDesc", "\u04afлкен процесс картасын \u049bарау терезесіне \u049bайтарады.\n" +
                                 "Егер \u04afлкен процесс болмаса, батырма басылмайды"},
            {"subProcessDesc", "Кіші процесті \u049bарау терезесін ша\u049bырады. Егер кіші\n" +
                               "процесс болмаса, батырма басылмайды"},
            {"debugProcessDesc", "Процесті ауыспалы м\u04d9ндеріні\u04a3 \u049bарау терезесін ша\u049bырады.\n" +
                                 "Батырманы Ж\u04afйені\u04a3 \u04d9кімшісі баса алады"},
            {"pwdChangeDesc", "Парольды ауыстыру диалогыны\u04a3 терезесін ша\u049bырады"},
            {"exchangeDesc", "Хабарды алу/ж\u04e8нелту іс-\u049bимылыны\u04a3 белсенді (орындаушы)\n" +
                             "процесіне бастамашы болады"},

            {"dataLangDesc", "Деректер тілін ауыстыру"},
            {"btnSrvDesc", "Процестерді басару режиміне к\u04e8шу"},
            {"btnArhDesc", "Дере\u049b\u049bорыны \u049bарау ж\u04d9не есептілікті \u049b\u04b1растыру режиміне к\u04e8шу"},
            {"btnSprDesc", "Нормативтік-аны\u049bтамалы\u049b а\u049bпаратпен ж\u04b1мыс істеу режиме к\u04e8шу"},

            {"baseLabelDesc", "Ж\u04afйені\u04a3 ж\u04b1мыс істеген дере\u049b\u049bорыны\u04a3 атауы"},
            {"userLabelDesc", "Ж\u04afйеге кірген пайдаланушыны\u04a3 аты"},
            {"taskTableDesc", "Пайдаланушы немесе байланысты а\u049bпаратты\u049b ж\u04afйе бастамашылы\u049b\n" +
                              "еткен белсенді тапсырмалар кестесі"},
            {"taskTableHeaderDesc", "Белсенді тапсырмалар кестені\u04a3 та\u049bырыбы. Кестені\u04a3 деректерін\n" +
                                    "с\u04b1рыптау м\u04afмкін, б\u04b1л \u04afшін тінтуірмен кестені\u04a3 ба\u0493аныны\u04a3 атауыны\u04a3\n" +
                                    "т\u04afрту \u049bажет"},
            {"counterLabelDesc", "Та\u04a3да\u0493ан тапсырманы\u04a3 номері мен белсенді\n" +
                                 "тапсырма жалпы саны"},
            //Main menu
            //File
            {"file", "&aФайл"},
            {"interface", "Интерфейс"},
            {"exit", "Шы\u0493у"},
            {"exitMenu", "&iШы\u0493у"},
            {"open", "Ашу"},
            {"openMenu", "&fАшу"},
            //Settings
            {"settings", "&,Бапталымдар"},
            {"interfaceLang", "&bИнтерфейс тiлi"},
            {"editorSetup", "u049aаріптер мен фон(каз)"},
            {"language", "Тілі...(каз)"},
            //Window
            {"window", "&nТерезелер"},
            {"taskMenu", "Та&gпсырмалар"},
            {"archiveMenu", "&vМ\u04b1ра\u0493ат"},
            {"catalogMenu", "А&yны\u049bтамалы\u049bтар"},
            //Help
            {"help", "&/?"},
            {"helpTip", "Ан&sы\u049bтама"},
            {"helpTipShort", "Аны\u049bтама"},
            {"helpTipLong", "Контекст аны\u049bтамасы"},
            {"helpTipDesc", "Сізді u049aызыu049aтыратын интерфейс<br/>элементін таu04a3даu04a3ыз"},
            {"helpMain", "Аны\u049bтама ж\u04e9не \u049aолдау"},
            {"about", "Т&eуралы"},
            {"helpMenu", "Ан&sы\u049bтама"},
            //
            {"reports", "Есеп хаттар"},
            {"beep", "&lДыбысты\u049b белгі"},
            {"scrollTabProc", "&pБетбелгілер скроллингі"},
            //Dialog buttons
            {"ok", "Жарайды"},
            {"cancel", "Болдырмау"},
            {"refresh", "Жа\u04a3арту"},
            {"yes", "И\u04d9"},
            {"no", "Жо\u049b"},
            {"clear", "Аластау"},
            {"close", "Жабу"},
            {"edit", "Табу"},
            {"continue", "Жал\u0493астыру"},
            {"save", "Са\u049bтау"},
            {"ignore", "Елемеу"},
            {"findBtn", "Табу"},
            {"deleteBtn", "М\u04d9ні жою"},
            {"create", "Жасау"},
            {"toBackground", "Фондыu049a режимде"},
            
            //Application title
            {"app", "ЗТ МД\u049a"},
            {"errors", "Енгізу \u049bателер"},

            //Messages title
            {"error", "\u049aате"},
            {"confirmation", "\u049a\u04b1птау"},
            {"message", "Хабар"},
            {"alert", "Ескерту"},
            {"option", "Сайлау"},
            {"enterPassword", "Пароль енгізі\u04a3iз"},

            //
            {"openInterfaceTip", "Интерфейс ашу"},
            {"openReportTip", "Есеп ашу"},
            {"nextStepTip", "Келесі \u049bадам"},
            {"killProcessTip", "Процесс болдырмау"},
            {"processesTab", "Процесстер"},

            //Messages
            {"exitMessage", "Ба\u0493дараламадан шы\u0493у\u0493а сенімдімісіз?"},
            {"killProcMessage", " Процесті болдырмау керек па?"},
            {"checkObjectMessage", "Объекті та\u04a3да\u04a3ыз"},
            {"ifcNotExistMessage", "Интерфейс та\u0493айындалма\u0493ан"},
            {"nextStepMessage", "Келесі \u049bадам?"},
            {"startProcMessage", "Процесті жегілу керек па"},

            //Labels
            {"datalang", " Деректер тілi:"},
            {"interfaceLangLabel", "Интерфейс тiлi:"},

            //RadioButtons
            {"rusShort", "орыс"},
            {"kazShort", "\u049bаз"},
            //Смена пароля
            {"oldPass", "Ескі пароль"},
            {"newPass", "Жа\u04a3а пароль"},
            {"confPass", "Растау"},
            {"passChangeTitle", "Парольды ауыстыру"},
            {"errorLoginMessage", "Пайдаланушыны\u04a3 аты немесе\n" + "паролі д\u04b1рыс емес!"},
            {"completeMessage", "Пароль ойда\u0493ыдай \u04e9згерiлдi."},
            {"newPassInvalidMessage", "Жа\u04a3а пароль енгiзiленген жо\u049b!"},
            {"oldPassInvalidMessage", "Ескi пароль \u049bате енгiзiленген!"},
            {"passNotEqualsMessage", "Парольдар д\u04d9л келген жо\u049b!"},
            {"notCompleteMessage", "Керек атрибуттар толтырылма\u0493ан!"},
            {"passwordTooShort", "Пароль %1% символдан кем\n" +
                                 "болмауы тиіс!"},
            {"passwordNotChanged", "Пароль \u04e9згерілген жо\u049b!"},
            {"passwordExpired", "Сізді\u04a3 пароль ескірді! Осы \u04d9зірде\n" +
                                "Сізге парольды \u04e9згертуге болады"},

            //LoginBox
            {"login", "Пайдаланушы:"},
            {"password", "Пароль:"},
            {"loginTitle", "Авторландыру"},

            //SelectServerParams
            {"srvName", "Атауы:"},
            {"host", "IP-адрес:"},
            {"port", "Порт:"},
            {"srvChange", "Серверді ауыстыру"},
            {"srvNoChanged", "Сервер туралы деректер u04e8згерген жоu049a"},

            //FilterDates Dialog
            {"filterDatesTitle", "Уа\u049bытты параметрлерді енгізі\u04a3із"},
            {"filterDatesBegin", "Бастап\u049bы кезені"},
            {"filterDatesEnd", "А\u049bыр\u0493ы кезені"},
            {"filterDatesCurrent", "Аu0493ымдаu0493ы кu04afні каз"},
            {"formReport", "2"},
            //TableNavigator
           {"fastRep", "Жылдам u04d9сер"},
           {"consal", "Жазбаны бiрiктiру"},
           {"add", "Жазбаны \u049bосу"},
           {"delete", "Жазбаны жою"},
           {"find", "Жазбаны табу"},
           {"filter", "С\u04b1згiнi \u049bолдану"},
           {"copyRows", "Тарма\u049bты к\u04e9шiру"},
           {"goDown", "Ж\u04b1ргiргiнi\u04a3 \u049bоз\u0493алысын ба\u0493ыттау"},
           {"moveDown", "Жолды төмен жылжыту"},
           {"moveUp", "Жолды жоu0493ары жылжыту"},
           {"showDeleted", "u049aашыu049aтаu0493ы мu04d9ндерді кu04e8рсету"},
           {"cancelApplyFilter","С\u04b1згiнi\u04a3 \u049bолданылуы\u04a3 болдырмау"},
           {"selectFilters","Сu04afзгіні таu04a3даu04a3ыз"},
            //login,password
           {"wrongLoginOrPassword","Пайдаланушыны\u04a3 аты немесе паролі д\u04b1рыс емес!"},
           {"userHasConnected", "Пайдаланушы ж\u04afйеге \u049bосыл\u0493ан!"},
           {"userHasConnectedSameIP", "Пайдаланушы ж\u04afйеге \u049bосыл\u0493ан! Жu04afйеге кіруді жалu0493астыру керек пе?"},
           {"serverDisconnect", "Сервермен байланыс жо\u049b!"},
           {"userIsBlocked", "Тіркелгі u04d9кімшімен u049au04b1лыптаулы!"},
            //Date formats and char
            {"mask", "кк.аа.жжжж"},
            {"mask1", "кк.аа.жжжж сс:ММ"},
            {"mask2", "кк.аа.жжжж сс:ММ:сс"},
            {"mask3", "кк.аа.жжжж сс:ММ:сс:ССС"},
            {"mask4", "сс:ММ:сс"},
            {"mask5", "сс:ММ"},
            {"mask6", "кк.аа"},
            {"charD", "к"},
            {"charM", "а"},
            {"charG", "ж"},
            {"charCH", "с"},
            {"charMM", "М"},
            {"charS", "с"},
            {"charSS", "С"},
           // FindRowPanel
           {"findTitle", "Жазбаны табу"},
           {"searchComplete", "Іздеу ая\u049bталды.\r\nЖазбы табыл\u0493ан жо\u049b!"},
           {"searchChooseColumn", "Іздеу ба\u0493аны та\u04a3даныз"},
           {"findRowInColumn", "ба\u0493анда\u0493ы жазбаны табу"},
           {"case", "Регистірді ескере отырып"},
           {"fullAnalog", "М\u04d9ндеріні\u04a3 толы\u049b с\u04d9йкестігімен"},
           {"firstSymbol", "Бастап\u049bы символдарыны\u04a3 с\u04d9йкестігімен"},
           {"containsStr", "u049au04b1рамында"},

           {"copiesCount", "К\u04e9шірме саны"},
           {"beforeAddAction", "Толы\u049bтыру алдында\u0493ы іс-\u049bимыл"},
           {"afterAddAction", "Толы\u049bтырудан кейінгі іс-\u049bимыл"},
           {"deleteRowsConfirm", "%1% жазбаны\u04a3 жойылуын раста\u04a3ыз!\n Жал\u0493астыру?"},
           {"deleteRowConfirm", "№ %1% жазбаны\u04a3 жойылуын раста\u04a3ыз!\n Жал\u0493астыру?"},
           {"beforeDeleteAction", "Жою алдында\u0493ы іс-\u049bимыл"},
           {"afterDeleteAction", "Жоюдан кейінгі іс-\u049bимыл"},
           {"afterMoveAction", "Орын ауыстырu0493аннан кейінгі іс-u04d9рекет"},
           // tree
           {"treeCollapse", "А\u0493ашты жабу"},
           {"treeExpand", "А\u0493ашты ашу"},
           {"renameNode", "Торапты \u049bайта атау"},
           {"changeNode", "Торап\u049bа бас\u049bа м\u04d9н та\u0493у"},
           {"createNode", "Торап пен м\u04d9н жасау "},
           {"createNodeBefore", "-"},
           {"createNodeAfter", "-"},
           {"createNodeAndBind", "Торап жасау ж\u04d9не м\u04d9н та\u0493у"},
           {"deleteNode", "Торапты жою"},
           {"expandNode", "Ашу"},
           {"collapseNode", "Жабу"},

           {"renameNodeTitle", "Элементті \u049bайта атау"},
           {"bindNodeTitle", "М\u04d9нді та\u04a3да\u04a3ыз"},
           {"createNodeTitle", "Жа\u04a3а объект жасау"},
           {"deleteNodeTitle", "Элемент(терді) жою?"},

           {"duplicateData", "Назар аудары\u04a3ыз! Деректер \u049bайталанады"},
           {"enterFolderName", "Папканы\u04a3 атауын енгізі\u04a3із"},
           {"enterElementName", "Элементті\u04a3 атауын енгізі\u04a3із"},
           {"enterIntCopyName", "Интерфейс к\u04e9шірмесіні\u04a3 атауын енгізі\u04a3із"},
           {"download", "Т\u04afсіру"},
           {"upload", "Ж\u04afктеу"},
           {"view", "\u049aарау"},
           {"fileNotFound", "Файл табылмады"},
           {"fileNotAppend", "Файл бекітілмеген"},
           {"fileUploader", "Файлды жu04afктеу"},

           {"upFolder", "Бір де\u04a3гейге жо\u0493ары"},
           {"createFolder", "Папка жасау"},
           {"list", "Тізім"},
           {"table", "Кесте"},
           {"findIn", "...-дан іздеу"},
           {"saveIn", "...-да са\u049bтау"},
           {"fileTypes", "Файлдарды\u04a3 \u04afлгілері"},
           {"fileName", "Файлды\u04a3 аты"},
           {"fileSize", "М\u04e9лшері"},
           {"fileType", "\u04aeлгісі"},
           {"fileDate", "К\u04afні"},
           {"fileAttr", "Атрибут"},
           {"desktop", "Ж\u04b1мысшы м\u04d9зір"},

           {"openFile", "Файлды ашу"},
           {"openFileTitle", "Файлды ашу"},
           {"docs", "Word, Excel \u049b\u04b1жаттар"},
           {"pictures", "GIF, JPG суреттер"},

           {"noname", "Аты жо\u049b"},
           {"nocomment", "Т\u04afсінік жо\u049b"},
           {"doc_saved","Өзгерiстер сәтті болып сақталынған!"},

           {"sendToDeveloper", "u04d9зірлеушіге жіберу"},
           
           //For Terminal use, rewrite it please
           {"run", "Орындау"},
           {"resetData", "Тастау"},
           {"clear2", "Тазалау"},
           {"clearConsole", "Консольді тазалау"},
           {"server", "Сервер"},
           {"client", "Клиент"},
           {"properties", "u049aасиеті"},
           {"informations", "Мu04d9ліметтер"},
           {"key", "кілт"},
           {"value", "мu04d9ні"},
           {"type", "тu04afрі"},
           {"process", "Процестер"},
           {"setHotKey", "ыстыu049a пернені таu0493айындау"},
           {"lastSrv", "Соu04a3u0493ы процестер"},
           {"runSrv", "Процестерді жегу"},
           {"searchSrv", "Процесті іздеу"},
           {"clickToSet", "Басумен таu0493айындау"},
           {"description", "Сипаттамасы"},
           {"next", "Бu04b1дан u04d9рі"},
           {"pleaseInsertWord", "u04e8тінеміз, сu04e8зді енгізіu04a3із"},
           {"withFolders", "Бумалармен"},
           {"contain", "u049au04b1рамында"},
           {"startsWith", "басталады"},
           {"endsWith", "аяu049aталады"},
           {"hotKeys", "Ыстыu049a пернелер"},
           {"search", "Іздеу"},
           {"not_found", "табылмады"},
           
           // верификация пароля
           {"validPwdMinLogin","Қолданушының аты X нышандардан аз болмау керек!"},
           {"validPwdMaxLogin","Пайдаланушының аты Х таңбаларынан кем болмайды!"},
           {"validPwdmMinPass","Пароль X нышандардан аз болмау керек!"},
           {"validPwdmMaxPass","Құпия сөз Х таңбаларынан артық болмайды!"},
           {"validPwdMinPassAdm","Администратор үшін пароль X нышандардан аз болмау керек!"},
           {"validPwdNoNumb","Парольде цифрлер қатысуы тиісті!"},
           {"validPwdNoAllNumb","Парольде цифрлер коп болмау керек!"},
           {"validPwdNoSymb","Парольде әріптер қатысуы тиісті!"},
           {"validPwdNoReg","Парольде әріптері әр түрлі регистрде болуы тиісті!"},
           {"validPwdNoSpec","Парольде арнайы нышандар қатысуы тиісті!"},
           {"validPwdNotName","Парольде қолданушының атыны қолдануға тыйым салынады!"},
           {"validPwdNotSurn","Парольде қолданушының фамилиясыны қолдануға тыйым салынады!"},
           {"validPwdNotTel","Парольде телефондардың нөмірлерін қолдануға тыйым салынады!"},
           {"validPwdNotWord","Парольде жиі қолданатын сөздерді қолдануға тыйым салынады!"},
           {"validPwdNotKeyboard","Парольде пернетақта сөздерін қолдануға тыйым салынады!"},
           {"validPwdNotRep","Құпия сөзде бірінші үш таңбалардың қайталануына тыйым салынады!"},
           {"validPwdNotRepAnyMoreTwo","Құпия сөзде қатар тұрған 2 таңбадан көп бірдей таңбалар қайталануына тыйым салынады!"},
           {"validPwdNotLogin","Парольде қолданушының логині қолдануға тыйым салынады!"},
           {"validPwdNotIdentificationData","Парольде жеке сәйкестендіру деректерін пайдалануға тыйым салынады!"},

           // сообщения авторизации пользователя
           {"messAccessDenied","Бағдарламаға кіруге тыйым салынады!\nСізге пароль ауыстыру қажет!"},
           {"messNotBD","Сізге жұмыс деректер қоры белгіленбеген. Өз администраторыңызға хабарласыныз."},
           {"messNotLangInf","Сізге интерфейс тілі белгіленбеген. Өз администраторынызға хабарласыныз."},
           {"messNotLangData","Сізге деректер қоры тілі белгіленбеген. Өз администраторынызға хабарласыңыз."},
           {"messFirstLogin","<html>Бұл Сіздің бірінші авторизацияңыз.<br>Парольді өзгерту қажет!"},
           {"messPassEnded","<html>Парольдің мерзімі аяқталды.<br>Парольді өзгерту қажет!"},
           {"messMinPeriodPass","Парольді тәулікте X реттен көп ауыстыруға тыйым салынады!"},
           {"messPassIdent","Енгізілген пароль бұрынғы парольды қайталамау керек!"},
           {"messPassDupl","Пароль бұрынғы X парольдерді қайталамау керек!"},
           {"recordNotActiv","Кіруге тыйым салынған!\nТіркелгіңіздің іске қосу уақыты өтті!"},

        // диаграмма
           {"notData","Көрсету үшін деректер жоқ!"},
           // Календарик
           {"okDate","Таңдауды растау"},
           {"cancelDate","Таңдауды болдырмау"},
           {"todayDate","Ағымдағыны орнату"},
           {"backMonth","Алдыңғы ай"},
           {"nextMonth","Келесі ай"},
           {"backYear","Алдыңғы жыл"},
           {"nextYear","Келесі жыл"},
           //
           {"delete2", "Жою"},
           
           {"key-choose-dialog-title", "Негізгі файлға жолды көрсетіңіз"},
           {"key-choose-button-title", "Таңдау"},
           {"key-choose-p12-desc", "PKCS 12 форматындағы ЭЦҚ кілттерінің файлдары"},
           {"key-choose-label", "Негізгі файл"},
           {"key-choose-tooltip", "ЭЦҚ кілті бар файлды таңдау"},

           {"firstPage", "Бірінші бет"},
           {"lastPage", "Соңғы бет"},
           {"nextPage", "Келесі бет"},
           {"backPage", "алдыңғы бет"},
           {"increase", "Үлкейту"},
           {"reduce", "Кішірейту"},

           {"send", "Жіберу"},
           {"webSend", "Аяқтау"},
           {"webStartPage", "Басты"},
           {"webMyProfile", "Менің жеке ісім"},
           {"webMonitor", "Үдеріс мониторы"},
           {"webOldFlows", "Бұрын іске қосылған процестер"},
           {"webProcesses", "Үдерістер"},
           {"webShtat", "Штаттық орналастыру"},
           {"webArchive", "Электрондық қойма"},
           {"webDicts", "Анықтамалар"},
           {"webStat", "Статистика"},
           {"webAdmins", "Технологиялық блок"},
           {"webRights", "Рұқсат алу құқықтары"},
           {"webUserAct", " Пайдаланушылар әрекеттерінің мониторингі"},
           {"webTasksIn", "Кіріс тапсырмалары"},
           {"webTasksOut", "Шығыс тапсырмалары"},
           {"webTasksMy", "Құжаттардың жобалары"},
           {"webTasksOld", "Құжаттардың бұрын жасалған жобалары"},
           {"webTasksOldWarning", "Сіз бұрын іске қосқан процестердің бар болуы туралы мәлімдеме!"},
           {"webTasksOldText1", "Жүйе Сізге Сіз бұрын іске қосқан процестердің тізімін ұсынады. Бұл процестер серверде белгілі бір ресурстарды алады."},
           {"webTasksOldText2", "Сервер ресурстарын үнемді пайдалану мақсатында Сізге әрбір іске қосылған процес бойынша келесі шешімдердің біреуін қабылдау қажет: жою немесе аяқтау."},
           {"webTasksOldText3", "Шешімдерді қабылдау кезеңі мәлімдемені алғаннан кейін"},
           {"webTasksOldText4", "күн."},
           {"webTooltips","Қалқып шығатын ишара жазу"},
           {"webNoteSound", "Хабарлама дауысы"},
           {"webInstantECP","Сессия уақытында құпия сөзді сақтаңыз"},
           {"webOn","Қосу"},
           {"webOff","Өшіру"},
           {"webSearchMain","Іздеу үшін сұрауды енгізіңіз"},
           {"webSearchTaskByName", "Тапсырманың атын енгізіңіз"},
           
           {"webNotification", "Хабарландыру"},
           {"webNotification2", "Кіруден кейінгі хабарламалар"},
           {"webPeriodNotification","Хабарландыру алған уақыты"},
           {"webStartDayNotification","Басталу күні"},
           {"webEndDayNotification","Аяқталу күні"},
           {"webNotificationTitle","Хабарлама"},
           {"webNotificationFrom","Жіберуші"},
           {"webNotificationInDate","Алынған"},
           {"webNotificationOpenDate","Ашылған"},
           {"webNotificationAwereDate","Танысқан"},

           {"webAvailProc", "Қолжетімді үдеріс тізімі"},
           {"webNSI", "Нормативті-анықтамалы ақпарат"},
           {"webSessions", "Пайдаланушылар сессиялары"},
           {"webProfile", "Пайдаланушы профилі"},
           {"webBirthday", "Туған күні"},
           {"webDetails", "Толығырақ"},
           {"webExit", "Шығу"},
           {"webPass", "Пароль"},
           {"webPassChange", "Ағымдағы парольді өзгерту"},
           
           {"webPhotoLoad", "Сурет жүктеу"},
           {"webPhotoDelete", "Суретті жою"},
           {"webPhotoTake", "Жеке істен алу"},

           {"webRoles", "Рөлдер"},
           {"webPosition", "Лауазымы"},
           {"webGO", "Мемлекеттік орган, құрылымдық бөлім"},
           {"webOrganization", "Ұйымдастыру"},
           {"webContacts", "Байланыс"},
           {"webTel", "Тел. ішкі"},
           {"webBreadcrumbs", "Навигациалық тізбек"},
           {"webLang", "Интерфейс тілі"},
           {"webTheme", "Түсқағаз"},
           {"webExpand", "Ашу"},
           {"webExpandAll", "Барлығын ашу"},
           {"webCollapse", "Ықшамдау"},
           {"webCollapseAll", "Барлығын ықшамдау"},
           {"webMoveUp", "Жоғары"},
           {"webMoveDown", "Tөмен"},
           {"webFavoriteProcesses", "Таңдаулы процестер"},
           {"webAddToFavorites", "Таңдаулыға қосу"},
           {"webRemoveFromFavorites", "Таңдаулынан жою"},

           {"webWait", "Күте тұрыңыз..."},
           {"webPassChangeTitle", "Парольді өзгерту"},
           {"webPassOld", "Ескі пароль"},
           {"webPassNew", "Жаңа пароль"},
           {"webPassConfirm", "Қайта енгізу"},
           {"webDlgOk", "OK"},
           {"webDlgClose", "Жабу"},
           {"webDlgCancel", "Болдырмау"},
           {"webDlgChange", "Өзгерту"},
           {"weDlgSave", "Сақтау"},
           {"webDlgContinue2", "Енгізуді жалғастыру"},
           {"webDlgContinue", "Жалғастыру"},
           {"webDlgIgnore", "Елемеу"},
           {"webErrors", "Мәліметтерді енгізу қателері"},
           {"webFilter", "Сүзгілеу"},
           {"webClear","Тазарту"},
           {"webFeature","Белгі"},
           {"webAll", "Барлығы"},
           {"webViewed","Қаралған"},
           {"webUnreviewed","Қаралмаған"},
           
           {"webSaving", "Мәліметтерді сақтау..."},
           {"webCanceling", "Өзгерiстерді болдырмау..."},
           {"webDeleting","Жою..."},
           {"webAlert","Хабар пайдаланушыға"},
           {"webRemoveProcess","Тапсырманы жоюға сенімдісіз бе?"},
           {"webRemoveProcess2","Тапсырмаларды жоюға сенімдісіз бе"},
           {"webProcStop", "Үдерісті тоқтату қажет пе?"},
           {"webAllCheckedProc", "Барлығын белгілеу"},
           {"webDeleteProcess", "Тапсырманы жою"},
           {"webSort","Сұрыптау:"},
           {"webChronology","Хронология бойынша"},
           {"webOverdue","Уақыты шығып кеткен бойынша"},
           {"webInFireCount","Уақыты шығып кеткен тапсырмалар саны"},
           {"webEnableListUpdate", "Жаңарту тізімін қосыңыз"},
           {"webDisableListUpdate", "Жаңарту тізімін өшіріңіз"},
           {"webShowUsedMemory", "Пайдаланылған жадты көрсету"},
           {"webUsedMemory", "Пайдаланылатын жады"},

           {"webHelp", "Анықтама"},
           {"webHelp1", "e-kyzmet дегеніміз не?"},
           {"webHelp2", "Жүйемен жұмыс істеудегі көмек"},
           {"webHelp3", "Жиі қойылатын сұрақтар"},
           {"webHelp4", "Нормативті-құқықтық актілер"},
           {"webAskNextStep", "Мәліметтерді ары қарай өңдеуге жіберуге сенімдісіз бе?"},

           {"webDlgSign", "Қолтаңба қою"},
           {"webKeyStore", "Кілттің орналасқан жері"},
           {"webPKCS12Files", "ЭЦҚ кілттерінің файлдары PKCS12 форматында"},
           
           {"webLastSuccesProcessDef", "Сіз соңғы рет үдерісті сәтті іске қостыңыз"},

           {"webLastSuccessfullTime", "Дата последнего успешного входа"},
           {"webLastUnsuccessfullTime", "Дата последней неуспешной попытки входа"},
           {"webRemoveSession","Вы уверены, что хотите удалить сессию?"},
           {"webRemoveSession2","Вы уверены, что хотите удалить сессии"},
           {"webDeleteSessionBtn","Отключить пользователей"},
           {"webSendMessageBtn","Отправить сообщение"},
           {"webSendMessageTitle","Отправка сообщения"},
           
           {"reloadProcess", "Процесті қайта жүктеу"},

           {"ipAddress", "IP-адрес"},
           {"IIN", "ЖСН"},
           {"rptGenerateMessage", "Есеп қалыптастырылуда"},
           {"procPerformedMessage", "Процедурасы орындалуда"},

           {"supportTeam", "Қолдау қызметі"},
           {"pingTime", "Жауап беру уақыты"},
           {"webHelpDocs", "Анықтамалық материалдар"},
           {"processEngaged", "Процесс находится на стадии обработки данных!"},
           {"processActive", "Выполняется предыдущее действие!"},
           {"processEngagedByUser", "Процесс находится на стадии обработки данных пользователем '{1}'!"},
           {"processStartTimeout", "Время ожидания открытия интерфейса истекло ({1} сек). Попробуйте позднее."},
           {"processStartError", "Ошибка при запуске процесса!"},
           {"processStateError", "Процесс находится в состоянии ошибки! Обратитесь к разработчику!"},
           {"processStepError", "Ошибка на шаге процесса!"},
           {"processNotFound", "Не найден запущенный процесс для данного задания! Обратитесь к разработчику!"},
           {"processManyFound", "Найдено {1} запущенных процессов для данного задания! Обратитесь к разработчику!"},
           {"olapAnalytic", "Аналитика"}
    };

    protected Object[][] getContents() {
        return contents;
    }
}