//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.19 at 10:39:04 AM ALMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://esb.sergek.kz/cxf/post-status", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kz.tamur.fc.kazpost.gep.status;
