//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.19 at 10:39:04 AM ALMT 
//


package kz.tamur.fc.kazpost.gep.status;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="onPostResponse" type="{http://esb.sergek.kz/cxf/post-status}onPostResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "onPostResponse"
})
@XmlRootElement(name = "Response")
public class Response {

    @XmlElement(required = true)
    protected OnPostResponse onPostResponse;

    /**
     * Gets the value of the onPostResponse property.
     * 
     * @return
     *     possible object is
     *     {@link OnPostResponse }
     *     
     */
    public OnPostResponse getOnPostResponse() {
        return onPostResponse;
    }

    /**
     * Sets the value of the onPostResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnPostResponse }
     *     
     */
    public void setOnPostResponse(OnPostResponse value) {
        this.onPostResponse = value;
    }

}
